### ISSUE TITLE
Wrong redirect in 'installation-guide' to the getting started

### ISSUE THREAD

**Issue by Yaymaha** [LIKO-12/legacy-2#17]
In 'What's next' it lead you to 'https://liko-12.github.io/#/./getting_started' which don't exist, it should lead you to 'https://liko-12.github.io/#/./Documentation/Guides/getting_started'

**Comment by Rami-Sabbagh** [comment]
I'm working on a new website that'll replace the current one, and it's coming together recently, finally giving proper documentation for LIKO-12 :)

You can preview the WIP website under http://liko-12.github.io/WIP/
